### PR TITLE
HYDRA-803 : add a test for Usd stage references and payloads

### PR DESCRIPTION
**Pull request by lanierd-adsk**

### CODE REVIEW

**Comment by lanierd-adsk** [comment]
FYI : @ppt-adsk @roopavr-adsk @vlasovi @debloip-adsk

**Comment by lanierd-adsk** [comment]
It is likely this test needs HYDRA-691 to be merged as without it it produces a crash. Let's see the preflight results.

**Comment by lanierd-adsk** [comment]
The preflight cannot pass yet, the fix is expected when HYDRA-691 is merged. But the code review can start anyway.

**Review by lilike-adsk — APPROVED** [review]

**Comment by lanierd-adsk** [comment]
Closing this PR and reopening a new PR based on the latest changes from maya hydra so the test can pass. They need the fix from HYDRA-691.

**Pull request closed without merging**
