### PR TITLE
HYDRA-803 - add test for payload & reference

### PR DESCRIPTION
**Pull request by lilike-adsk**
add test for payload & reference

### CODE REVIEW

**Comment by lilike-adsk** [comment]
FYI. @roopavr-adsk @ppt-adsk @vlasovi

**Review by debloip-adsk — APPROVED** [review]
Approving with a minor comment for the future : I think we should generally strive to have the objects in reference images take up a decent amount of space, so that we can detect potentially more subtle errors, e.g. the OSX one we've been having. I was a bit surprised to see we didn't need special OSX thresholds on this test, though I'm not sure if that's actually due to some of the images having small objects or instead due to using USD meshes.

**Comment by lilike-adsk** [comment]
> Reference in n

there're no wires rendered, that's why it survived on Mac

**Comment by debloip-adsk** [comment]
Ah true, forgot about that specificity, thanks!

**Pull request merged**
